/* Auto-generiert aus src/provider-presets.json - nicht von Hand editieren.
   Neu erzeugen: npm run presets   |   Prüfen (CI): npm run presets:check */
window.PROVIDER_PRESETS = [
  {"name":"OpenCode Zen","url":"https://opencode.ai/zen/v1","format":"openai"},
  {"name":"Kilo Gateway","url":"https://api.kilo.ai/api/gateway/","format":"openai"},
  {"name":"OpenAI","url":"https://api.openai.com/v1","format":"openai"},
  {"name":"Anthropic","url":"https://api.anthropic.com","format":"anthropic"},
  {"name":"DeepSeek","url":"https://api.deepseek.com","format":"openai"},
  {"name":"Kimi (Moonshot)","url":"https://api.moonshot.ai/v1","format":"openai"},
  {"name":"xAI (Grok)","url":"https://api.x.ai/v1","format":"openai"},
  {"name":"Groq","url":"https://api.groq.com/openai/v1","format":"openai"},
  {"name":"Ollama (Local)","url":"http://localhost:11434/v1","format":"openai"},
  {"name":"LM Studio (Local)","url":"http://localhost:1234/v1","format":"openai"},
  {"name":"vLLM (Local)","url":"http://localhost:8000/v1","format":"openai"},
  {"name":"Mistral AI","url":"https://api.mistral.ai/v1","format":"openai"},
  {"name":"Z.AI (Zhipu)","url":"https://api.z.ai/api/paas/v4/","format":"openai"},
  {"name":"Zhipu BigModel (CN)","url":"https://open.bigmodel.cn/api/paas/v4/","format":"openai"},
  {"name":"Gemini","url":"https://generativelanguage.googleapis.com/v1beta/openai","format":"openai"},
  {"name":"OpenRouter","url":"https://openrouter.ai/api/v1","format":"openai"},
  {"name":"MiniMax","url":"https://api.minimax.io/v1","format":"openai"},
  {"name":"Qwen (Alibaba)","url":"https://dashscope-intl.aliyuncs.com/compatible-mode/v1","format":"openai"},
  {"name":"Together AI","url":"https://api.together.ai/v1","format":"openai"},
  {"name":"Fireworks AI","url":"https://api.fireworks.ai/inference/v1","format":"openai"},
  {"name":"DeepInfra","url":"https://api.deepinfra.com/v1/openai","format":"openai"},
  {"name":"Perplexity (Sonar)","url":"https://api.perplexity.ai","format":"openai"},
  {"name":"Cohere","url":"https://api.cohere.ai/compatibility/v1","format":"openai"},
  {"name":"AI21 (Jamba)","url":"https://api.ai21.com/studio/v1","format":"openai"},
  {"name":"Cerebras","url":"https://api.cerebras.ai/v1","format":"openai"},
  {"name":"SambaNova","url":"https://api.sambanova.ai/v1","format":"openai"},
  {"name":"Hyperbolic","url":"https://api.hyperbolic.xyz/v1","format":"openai"},
  {"name":"Novita AI","url":"https://api.novita.ai/openai/v1","format":"openai"},
  {"name":"Baseten","url":"https://inference.baseten.co/v1","format":"openai"},
  {"name":"Hugging Face Router","url":"https://router.huggingface.co/v1","format":"openai"},
  {"name":"NVIDIA NIM","url":"https://integrate.api.nvidia.com/v1","format":"openai"},
  {"name":"Baidu ERNIE (Qianfan)","url":"https://qianfan.baidubce.com/v2","format":"openai"},
  {"name":"ByteDance Volcano Ark","url":"https://ark.cn-beijing.volces.com/api/v3","format":"openai"},
  {"name":"Tencent Hunyuan","url":"https://api.hunyuan.cloud.tencent.com/v1","format":"openai"},
  {"name":"StepFun","url":"https://api.stepfun.com/v1","format":"openai"},
  {"name":"SenseNova (SenseTime)","url":"https://token.sensenova.cn/v1","format":"openai"},
  {"name":"Vercel AI Gateway","url":"https://ai-gateway.vercel.sh/v1","format":"openai"},
  {"name":"Requesty","url":"https://router.requesty.ai/v1","format":"openai"},
  {"name":"Martian","url":"https://api.withmartian.com/v1","format":"openai"},
  {"name":"Reka AI","url":"https://api.reka.ai/v1","format":"openai"},
  {"name":"Featherless AI","url":"https://api.featherless.ai/v1","format":"openai"},
  {"name":"NanoGPT","url":"https://nano-gpt.com/api/v1","format":"openai"},
  {"name":"Chutes","url":"https://llm.chutes.ai/v1","format":"openai"},
  {"name":"Venice AI","url":"https://api.venice.ai/api/v1","format":"openai"},
  {"name":"iFlytek Spark","url":"https://spark-api-open.xf-yun.com/v1","format":"openai"},
  {"name":"Kimi China (Moonshot)","url":"https://api.moonshot.cn/v1","format":"openai"},
  {"name":"Kimi Code (Subscription)","url":"https://api.kimi.com/coding/v1","format":"openai"},
  {"name":"Z.AI GLM Coding (Anthropic)","url":"https://api.z.ai/api/anthropic","format":"anthropic"},
  {"name":"Jan (Local)","url":"http://127.0.0.1:1337/v1","format":"openai"},
  {"name":"GPT4All (Local)","url":"http://localhost:4891/v1","format":"openai"},
  {"name":"LocalAI","url":"http://localhost:8080/v1","format":"openai"},
  {"name":"text-generation-webui (Local)","url":"http://127.0.0.1:5000/v1","format":"openai"},
  {"name":"KoboldCpp (Local)","url":"http://localhost:5001/v1","format":"openai"},
  {"name":"Nebius Token Factory","url":"https://api.tokenfactory.nebius.com/v1/","format":"openai"},
  {"name":"Crusoe Cloud","url":"https://api.inference.crusoecloud.com/v1","format":"openai"},
  {"name":"AI/ML API","url":"https://api.aimlapi.com/v1","format":"openai"},
  {"name":"Glama","url":"https://glama.ai/api/gateway/openai/v1","format":"openai"},
  {"name":"AiHubMix","url":"https://aihubmix.com/v1","format":"openai"},
  {"name":"CometAPI","url":"https://api.cometapi.com/v1","format":"openai"},
  {"name":"Portkey AI Gateway","url":"https://api.portkey.ai/v1","format":"openai"},
  {"name":"LiteLLM Proxy (Local)","url":"http://localhost:4000","format":"openai"},
  {"name":"Azure OpenAI","url":"https://YOUR-RESOURCE-NAME.openai.azure.com/openai/v1/","format":"openai"},
  {"name":"Amazon Bedrock","url":"https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1","format":"openai"},
  {"name":"Sarvam AI","url":"https://api.sarvam.ai/v1","format":"openai"},
  {"name":"Krutrim (Ola)","url":"https://cloud.olakrutrim.com/v1","format":"openai"},
  {"name":"OVHcloud AI Endpoints","url":"https://oai.endpoints.kepler.ai.cloud.ovh.net/v1","format":"openai"},
  {"name":"Scaleway","url":"https://api.scaleway.ai/v1","format":"openai"},
  {"name":"Google Vertex AI","url":"https://aiplatform.googleapis.com/v1/projects/PROJECT-ID/locations/global/endpoints/openapi","format":"openai"},
  {"name":"Akash ML","url":"https://api.akashml.com/v1","format":"openai"},
  {"name":"302.AI","url":"https://api.302.ai/v1","format":"openai"},
  {"name":"Tencent TokenHub","url":"https://tokenhub.tencentmaas.com/v1","format":"openai"},
  {"name":"Ollama Cloud","url":"https://ollama.com/v1","format":"openai"},
  {"name":"llamafile (Local)","url":"http://localhost:8080/v1","format":"openai"},
  {"name":"IONOS AI Model Hub","url":"https://openai.inference.de-txl.ionos.com/v1","format":"openai"},
  {"name":"Meituan LongCat","url":"https://api.longcat.chat/openai/v1","format":"openai"},
  {"name":"Xiaomi MiMo","url":"https://api.xiaomimimo.com/v1","format":"openai"},
  {"name":"SAKURA Internet","url":"https://simpleai.is1.api.sacloud.jp/v1","format":"openai"},
  {"name":"Upstage Solar","url":"https://api.upstage.ai/v1","format":"openai"},
  {"name":"HyperClova X (Naver)","url":"https://clovastudio.stream.ntruss.com/v1/openai","format":"openai"},
  {"name":"Aleph Alpha","url":"https://api.aleph-alpha.com/v1","format":"openai"},
  {"name":"StackIT AI Model Serving","url":"https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1","format":"openai"},
  {"name":"Maritaca AI","url":"https://chat.maritaca.ai/api","format":"openai"},
  {"name":"SiliconFlow","url":"https://api.siliconflow.cn/v1","format":"openai"},
  {"name":"PPIO","url":"https://api.ppio.com/openai/v1","format":"openai"},
  {"name":"ModelScope","url":"https://api-inference.modelscope.cn/v1/","format":"openai"},
  {"name":"01.AI (Yi)","url":"https://api.lingyiwanwu.com/v1","format":"openai"},
  {"name":"Baichuan AI","url":"https://api.baichuan-ai.com/v1","format":"openai"},
  {"name":"YandexGPT","url":"https://llm.api.cloud.yandex.net/v1","format":"openai"},
  {"name":"GigaChat (Sber)","url":"https://api.giga.chat/v1","format":"openai"},
  {"name":"NVIDIA NIM (Local)","url":"http://localhost:8000/v1","format":"openai"},
  {"name":"Huawei PANGU (MaaS)","url":"https://api-ap-southeast-1.modelarts-maas.com/openai/v1","format":"openai"}
];
